image: calces/drone-rails-postgres-redis-node-and-phantomjs

pipelines:
  default:
    - step:
        script:
          - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/pipelines
          - apt-get update
  branches:
    develop:
      - step:
          script:
            - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/pipelines
            - apt-get update
            - apt-get install -y npm
            - bundler --version
            - bundle install
            - rspec
            - rubocop
          services:
            - postgres
            - chromedriver
    feature:
      - step:
          script:
            - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/pipelines
            - apt-get update
            - apt-get install -y npm
            - bundler --version
            - bundle install
            - rspec
            - rubocop
          services:
            - postgres
            - chromedriver

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: pipelines
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user_password
    chromedriver:
      image: selenium/standalone-chrome
      ports:
        - "4444:4444"
        - "5900:5900"