# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 679bfa96414c7912c7c673d520faa5e3db1a7b72028e5850a602b0f0ac799b9b797875d2a7e3c44932ade917b07d44ba9ff34c72fde33d92638e7f2958464dda

test:
  secret_key_base: 1d1acc41cf137dedff8c65e62b712fc107957c45b6fa4d50fdd4d75c03fce79ecccd2b66e5c61f9b9c813c80daf66f7a53ff0044539423a5a58918d106e394d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
